### ISSUE TITLE
Plugin/theme headers (metadata) support

### ISSUE THREAD

**Issue by bibz** [loco/wp-loco#6]
The plugin/theme metadata is not extracted for translations.

For instance, [using the Wordpress `makepot.php` utility](https://developer.wordpress.org/plugins/internationalization/localization/#wordpress-i18n-tools), one obtains the following new strings for the wp-loco plugin:
```po
#. Plugin URI of the plugin/theme
msgid "http://wordpress.org/extend/plugins/loco-translate"
msgstr ""

#. Description of the plugin/theme
msgid "Translate Wordpress plugins and themes directly in your browser"
msgstr ""

#. Author of the plugin/theme
msgid "Tim Whitlock"
msgstr ""

#. Author URI of the plugin/theme
msgid "http://localise.biz/help/wordpress/translate-plugin"
msgstr ""
```

As per the [actual metadata extractor](https://develop.svn.wordpress.org/trunk/tools/i18n/pot-ext-meta.php) (called by `makepot.php`), the following are extracted:
- Plugin/Theme Name
- Plugin/Theme URI
- Description
- Author
- Author URI
- Tags

It seems that the extraction is handled by the *LocoPHPExtractor* class, which is compiled into `lib/build/gettext-compiled.php`.

Would it be possible to also take into account those strings?
(They are currently removed from the POT file on each sync.)

**Comment by timwhitlock** [comment]
Thanks for this. It has been mentioned before and is on the list of improvements

**Comment by timwhitlock** [comment]
I've added this metadata support into the current dev version which will become 1.5.4.

Also supports `Template Name: ..` headers in template files.
